### ISSUE TITLE
Add new liquidity SLA parameters

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#1024]
## Story

As a user 
I want to know the new liquidity SLA params for markets I might provide liquidity on
So that I know what will be expected of me if I provide liquidity on them

## Acceptance Criteria

- Add the market.liquidity.priceRange taken from the markets API
- Add the market.liquidity.commitmentMinTimeFraction from the markets API

## Mockup column

**Liquidity SLA**

Volume within 5% of midprice
Minimum 40% time on book

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by ciaran-** [comment]
@JonRay15 do we want these as new columns (combined or separate) or part of an existing one?

**Comment by JonRay15** [comment]
Deployed
