### ISSUE TITLE
LP tile suggestions on homepage

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#1110]
## The Chore

Per David 

While we’re on the topic: the liquidity “supplied 500 (100% of target)” isn’t very helpful, for the market to run we always need supplied stake > than target stake so it’s pretty much always going to be more than 100%. 

The green slider is nice but I am not sure what it’s telling me.

My suggestion on the liquidity part:
- ditch the percentage
- ditch the green slider
- add total LP fees paid in last epoch (in USDT) for a given market
- add total LP rewards paid in last epoch (in Vega) for a given market - if we want to give this more visibility.

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by goslingo** [comment]
@JonRay15 does this ticket need refining, or something we can start on?

**Comment by JonRay15** [comment]
Adding to the backlog ... we need to go through it soon.
