### ISSUE TITLE
Wrong font-family for fallback font on russian version of main page 

### ISSUE THREAD

**Issue by GreyPK** [vegaprotocol/vega.xyz#1113]
## Description
If I opened russian version of main page I see that the fonts have serifs. Your sans-serif font "AlphaLyrae" is not able to russian symbols, that's why fallback fonts work. The problem is that the fallback fonts are used with serifs, you need to fix them to sans serif fonts to maintain a consistent style.

## Steps to Reproduce

Open russian version of main page https://vega.xyz/ru/

## Expected behavior

All fonts must be sans-serif

## Screenshots
What I see (fallback serif font):
![Screenshot_1](https://github.com/vegaprotocol/vega.xyz/assets/9148071/6432b6a0-fe9c-44dc-95ed-7ea9a58daef5)

What should be (After css fix):
![Screenshot_2](https://github.com/vegaprotocol/vega.xyz/assets/9148071/d312287f-97e0-4845-9183-2c275d146676)

## Device details

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest

## To fix:
In file src\css\index.css line 15:
```
body {
  font-family: 'AlphaLyrae', georgia, serif;
}
```
change to something like:
```
body {
  font-family: 'AlphaLyrae', sans-serif;
}
```
I can create pull request if needed with fixed css

**Comment by goslingo** [comment]
Thanks for spotting this @GreyPK  🙏
