### ISSUE TITLE
Add News article

### ISSUE THREAD

**Issue by rebeccajsimmonds** [vegaprotocol/vega.xyz#1116]

**Comment by rebeccajsimmonds** [comment]
Add this link to articles

https://www.theblock.co/post/263704/vega-protocol-unveils-decentralized-perpetuals-on-trading-blockchain

and it should show up on the homepage as well

**Comment by goslingo** [comment]
![Image](https://github.com/vegaprotocol/vega.xyz/assets/1823553/36754232-b07c-4b84-ac4b-b6f11bde751c)
