### ISSUE TITLE
Add the links to the console deployments to the interstitial page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#1136]
## The Chore

When we had that vegaprotocol.eth outage no one could access Console.

We should provide a link to the console deployments so that users have a workaround if that happens again.

Based on prior discussion I dont think there is a decentralisation issue from doing that.

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by edd** [comment]
Already exists

<img width="1151" alt="Screenshot 2024-01-04 at 12 14 30" src="https://github.com/vegaprotocol/vega.xyz/assets/6678/2ef01e7d-dec8-41f9-b36b-ff2bfa0fb9a5">
