### ISSUE TITLE
A strange 0 infront of staking number of website

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/vega.xyz#1154]
## Description

Check vega.xyz and see the staking number, a strange 0 in front of the number.

<img width="1079" alt="Screenshot 2024-02-26 at 12 43 13" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/6bed12a0-935a-4201-ac44-ea5665fc67cb">

**Comment by goslingo** [comment]
I can't replicate, is it still an issue @rebeccajsimmonds ?
