### ISSUE TITLE
👯 Builders club landing page

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#189]
## Story

As the community team 
We want to have a dedicated home for builders club that clearly explains what it is, why you should join, what's going on and how to join 
So that we can point people there easily, provide something to link to from our beer mats etc, generally make it easier to get more people "in". 

## Acceptance Criteria

- [ ] There's a new dedicated landing page for the builders club (see sketch)
   - [ ]  Header and key CTAs
   - [ ]  Notification / call out to the free builders course 
   - [ ]  Repurposed events module, show first 5 upcoming, filtered for builders club only events (AMAs and Hackathons) with cta to all events
- [x]  We've used the new branding (blurple keynote attached by [@David R](https://app.asana.com/0/1201845882167123/board))
- [ ] There's a way to find out more about the ambassadors program in general
- [ ] The URL is easy to remember / share i.e. /buildersclub (but that could be achieved through redirects as that's not necessarily how the site is structured?) 
- [ ] We've made it clearer how to join one team or another of the ambassadors program on the ambassadors page i.e. two columns, two apply buttons 
- [ ] There's a way to apply directly to the builders club and a link to find out more / see what's going on on the ambassadors page (this effects the one column / two column / sticky button thing)
- [ ] We've updated the links from discord to the new builders club page
   - [ ] on the community landing page
   - [ ] In the header (under community and develop) 
   - [ ] In the footer

## Sketch

![Image](https://user-images.githubusercontent.com/47143694/190851021-01dd2d70-8fa2-483a-9369-8d4be3539709.png)

![Image](https://user-images.githubusercontent.com/47143694/190851012-1ae35eb2-0bcb-4929-9525-77f0da1844cd.png)

Link to Builders Club Templates keynote in Drive https://drive.google.com/file/d/191HCxNILgXBhXQI_08m3igZQ8FMUN7YL/view?usp=sharing

**Comment by pennyandrews** [comment]
Being slightly opportunistic here @bigfandavid @joellecharlotte @goslingo if we are adding / amending the footer as part of this story could we take a look at the footer layout for mobile and see if we can tidy it up a little... as the community list has grown lots it is starting to look a little unbalanced.

![Image](https://user-images.githubusercontent.com/47143694/190853846-e1f2988b-ad89-44e0-80e2-2404dd92c8e0.png)

**Comment by bigfandavid** [comment]
XL Visual. Signed off and now moving forward to responsive versions once Joelle has looked at consistent title sizes/styles.

![Image](https://user-images.githubusercontent.com/113683891/191709825-93bd269a-3e96-41be-9c5a-3dc928eba73e.png)



![Image](https://user-images.githubusercontent.com/113683891/191709795-bf83d79c-f07f-4cdf-a56c-3187de8e8bf0.jpg)

**Comment by ckpringle** [comment]
Review: 
* Link to builders club to be updated under "community" to link to this page
* The secondary (?) CTA / link at the bottom looks very small, is it the right size?
* Something funky about the events table on mobile (see attached)
* I think the "see more" button wasn't in the design - duplicates functionality of the view all events so not needed

![Image](https://user-images.githubusercontent.com/46783148/195288614-4eb75494-491f-42af-86d5-db1284b317a3.png)

**Comment by goslingo** [comment]
@ckpringle 

> The secondary (?) CTA / link at the bottom looks very small, is it the right size?

It is the correct size

> I think the "see more" button wasn't in the design - duplicates functionality of the view all events so not needed - interestingly the view all button doesn't appear on mobile though, only see more?

There wasn't a mobile design provided for this area of the page. But it felt more logical to hide the "View all events" button from showing on the mobile view as it would sit above the list.

The <Calendar> component already provides a "See more" button at the bottom on the mobile view (you'll see it as it appears on the home page). I think it makes sense to keep it there as we hide the button at the top.

**Comment by goslingo** [comment]
https://deploy-preview-233--vega.netlify.app/builders-club
