### ISSUE TITLE
🏆 Rewards landing page (+ incentive / bounty changes)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#194]
## Story

As a user 
I want to easily see all the ways I could earn rewards on Vega and the reward totals 
So that I can understand what things I can earn rewards for and the sort of value we are talking about

## Acceptance Criteria 

- [x] There is a list of reward types 
- [ ] I can see paid out reward totals per epoch for Trading, Liquidity Provision, Market Creation
- [ ] I can see current APY for staking
- [ ] I can see total rewards committed for this epoch
- [ ] We've worked out how the numbers get in here - via integration with data node. May require a couple of queries and basic maths like dividing a number by another or something - which could be done client side or with a small service
- [x] There is a link to create your own reward (linking to the docs - https://docs.fairground.vega.xyz/docs/trading-questions/#trading-rewards or is it on the new docs site)
- [x] There are CTAs to where you go to do the thing you can earn the reward for
- [x] There's a link to token frontend rewards page to see the rewards I've earned
- [ ] We've worked out how the layout should work if one of the reward types isn't available
- [x] We've added the page link to the navigation (header and footer!) under "get rewarded" 
- [x] Under "get rewarded" in the global nav we want to replace "Incentives and bounties" with  "Fairground incentives ↗" to link directly to fairground.wtf and "Bounties ↗" to link directly to https://github.com/vegaprotocol/bounties/
- [x] We have removed the incentives and bounties page under Develop and Community

Can we sweep up this visual bug whilst implementing this card #200 

## Sketch

![Image](https://user-images.githubusercontent.com/47143694/190716573-0785b115-089b-4f9c-b417-d63076195f63.png)

## Integration notes

GraphQL URL: https://api.n12.testnet.vega.xyz/api/v2/rewards contains what we need to calculate the reward averages.

**For Trading rewards:** rewardAccountTypes = types.AccountTypeMakerPaidFeeReward
**For Liquidity Provision rewards:** rewardAccountTypes = types.AccountTypeLPFeeReward
**For Market Creation rewards:** rewardAccountTypes = types.AccountTypeMarketProposerReward

Example script to calculate a total amount of a reward type per epoch, per asset (suggest we calculate an average over 7 days) e.g. ACCOUNT_TYPE_FEES_INFRASTRUCTURE

```
import urllib.request
import json
decoded = json.loads(urllib.request.urlopen("https://api.n12.testnet.vega.xyz/api/v2/rewards").read())
asset_to_infra = {}
global_reward = 0
global_reward_asset = ""
#find last epoch first
max_epoch = -1 
for node in decoded["rewards"]["edges"]:
	epoch = node["node"]["epoch"]
	if int(epoch) > max_epoch:
		max_epoch = int(epoch)
for node in decoded["rewards"]["edges"]:
	epoch = int(node["node"]["epoch"])
	if epoch == max_epoch and node["node"]["percentageOfTotal"] != "0" and node["node"]["assetId"] not in asset_to_infra and node["node"]["rewardType"] == "ACCOUNT_TYPE_FEES_INFRASTRUCTURE":
		total_reward = float(node["node"]["amount"])/(float(node["node"]["percentageOfTotal"])/100.0)
		asset_to_infra[node["node"]["assetId"]]	= total_reward
	elif epoch == max_epoch and node["node"]["percentageOfTotal"] != "0" and node["node"]["rewardType"] == "ACCOUNT_TYPE_GLOBAL_REWARD":	
		global_reward = float(node["node"]["amount"])/(float(node["node"]["percentageOfTotal"])/100.0)
		global_reward_asset = node["node"]["assetId"]
print("epoch,asset,rewardType,amount")
for key, value in asset_to_infra.items():
	print(max_epoch,",", key,",", "ACCOUNT_TYPE_FEES_INFRASTRUCTURE", ",",value)
if global_reward_asset != "":
	print(max_epoch,",", global_reward_asset,",", "ACCOUNT_TYPE_GLOBAL_REWARD",",", global_reward)	
```

Outputs 

```
epoch,asset,rewardType,amount
889 , 5cfa87844724df6069b94e4c8a6f03af21907d7bc251593d08e4251043ee9f7c , ACCOUNT_TYPE_FEES_INFRASTRUCTURE , 3.000000000000001
889 , 8b52d4a3a4b0ffe733cddbc2b67be273816cfeb6ca4c8b339bac03ffba08e4e4 , ACCOUNT_TYPE_FEES_INFRASTRUCTURE , 3.000000000000001
```

Miro for reference https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764531263199100&cot=14

**Comment by pennyandrews** [comment]
Joëlle:

Here is the first pass at this page, some colour is needed but thinking this could be introduced in bespoke imagery in the top cards depending on whether this is the right approach or not.

![Image](https://user-images.githubusercontent.com/47143694/190716746-2e644fac-5d62-4400-9c25-a5e444797881.png)

There are a couple of questions in the [Figma file ](https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=770%3A27434)(the pink / yellow post-its)

Probably good to review this over a call!

**Comment by pennyandrews** [comment]
Joëlle:

A couple of options in the [Figma file](https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=794%3A28249).

[@David R](https://app.asana.com/0/1201845882167123/list) will review early next week
[@Oliver Gosling](https://app.asana.com/0/1201845882267642/list) will commence work on this likely on Wednesday

Comment from [@Neil Dawson](https://app.asana.com/0/1202629052286729/list) to think about how to make the epoch countdown feel like a countdown (animation is one approach)

I will look at an alternative design that doesn't rely on a progress bar and is a bit more static to minimise dev work if required.

![Image](https://user-images.githubusercontent.com/47143694/190716812-8d2b6a84-0a1f-48ae-82e7-9dafa3919110.png)

**Comment by ckpringle** [comment]
Making some progress on calculating APY here: https://docs.google.com/spreadsheets/d/149qcr9wTr-Wbdx5w94mwSdWpP95WsQJyj-Ut90vRGsI/edit#gid=581991856 but **still dependent on** someone from Core / Datanode / Research to specify 

- The API and field name to source staking rewards in $VEGA paid out in the last epoch
- The API and field name to source the infrastructure fees paid out for each settlement asset in the last epoch

CC @pennyandrews

**Comment by ckpringle** [comment]
For calculating trading / LP and market creation rewards we're stuck on needing  

- the total amount of rewards (in VEGA only) paid out based on maker fees paid in the previous epoch
- the total amount of rewards (in VEGA only) paid out based on LP fees earned in the previous epoch
- the total amount of rewards (in VEGA only) paid out based on Market Creation in the previous epoch
- And for all of them we might want to average that over X number of epochs (but I dont think too many and we could probably manage that in the front end?)

CC @pennyandrews

**Comment by ckpringle** [comment]
Build preview https://deploy-preview-185--vega.netlify.app/rewards

**Comment by ckpringle** [comment]
Links to be updated 
* "Create your own reward" should link to https://docs.vega.xyz/testnet/concepts/trading-on-vega/fees-rewards#setting-rewards
* "Provide liquidity" should link to https://docs.vega.xyz/testnet/tutorials/committing-liquidity
* "Become a validator" should link to https://docs.vega.xyz/testnet/node-operators/setup-validator
