### ISSUE TITLE
Flag Wendy concept as coming soon

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#216]
## The Chore

Add comment / flag / something to indicate that Wendy is 'coming soon' to key concepts - it has just been prototyped currently and isn't live / in use with the network (agreed to otherwise park tagging the individual concepts by status)

## Tasks

- [X] Design
- [X] Team review
- [ ] Share with vega
- [ ] Implement
- [ ] Team testing
- [ ] Release

## Additional details / background info

<img width="1302" alt="Screenshot 2022-08-04 at 15 18 51" src="https://user-images.githubusercontent.com/47143694/191125672-efa81354-a413-4949-8fbf-be652220b98a.png">

**Comment by pennyandrews** [comment]
Joëlle:

See the suggested solution [here →](https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=243%3A17863)

I thought a little pill saying "COMING SOON" could be used to signpost things like this.

I've turned off the other layers in the frame that had outdated content (for now) and updated the content on the page to match what is live. This was to help me design to the current implementation rather than an older version - though I know that typically we shouldn't have to have the Figma files updated with latest content as this is bound to change regularly.

LMK what you think.

**Comment by pennyandrews** [comment]
Calum:

I think that does the job for now yes thanks

**Comment by pennyandrews** [comment]
Joëlle:

Assigned to David to have a look 🙂

**Comment by pennyandrews** [comment]
David:

Looks good 🤩 - I think we should turn off the contextual alternatives for text at this size.

**Comment by pennyandrews** [comment]
Joëlle:

Have updated the "pill" so it does not included the contextual alternatives.

**Comment by pennyandrews** [comment]
@joellecharlotte will need to update the link to the designs for this ticket with the new location in the design system

**Comment by joellecharlotte** [comment]
[Here's the updated link](https://www.figma.com/file/2ID8fjvalQv98vd7uHRuge/Learn?node-id=673%3A39226) (also updated in the comment above for completeness)
