### ISSUE TITLE
Latest tweet is showing image from previous tweet

### ISSUE THREAD

**Issue by goslingo** [vegaprotocol/vega.xyz#227]
## Description

The latest tweet shows an image from the previous tweet.

## Steps to Reproduce

1. Go to [Homepage](https://www.vega.xyz)
2. View latest news

## Expected behavior

The latest tweet should show the correct image.

## Screenshots
<img width="435" alt="Screenshot 2022-09-21 at 11 05 28" src="https://user-images.githubusercontent.com/1823553/191477085-955ff006-bb14-4864-b8a0-58102cc4f8b2.png">
<img width="615" alt="Screenshot 2022-09-21 at 11 05 48" src="https://user-images.githubusercontent.com/1823553/191477097-6eeae447-9193-4a40-ac4f-897e424aeca3.png">

**Comment by goslingo** [comment]
It seems this bug is still happening...

https://twitter.com/vegaprotocol/status/1582347907738763269

<img width="344" alt="Screenshot 2022-10-18 at 13 37 08" src="https://user-images.githubusercontent.com/1823553/196431173-4a62844d-23db-48f6-9a4a-2dae19715ff4.png">

**Comment by ckpringle** [comment]
Still a problem 

![Image](https://user-images.githubusercontent.com/46783148/200900693-0446e224-89a3-4693-b228-5b21750d8778.png)
![Image](https://user-images.githubusercontent.com/46783148/200900691-b3aaf329-6cbe-476a-b9cd-5b0f5e302cc5.png)

**Comment by goslingo** [comment]
@ckpringle did you use the preview link here: https://deploy-preview-262--vega.netlify.app/

I'm seeing the below, which is technically correct. The tweet itself doesn't have an image (although Twitter does pull out the image preview from the embedded link).

<img width="426" alt="Screenshot 2022-11-09 at 17 53 09" src="https://user-images.githubusercontent.com/1823553/200904247-895c04a6-a250-4218-9813-976e760c5c45.png">
