### ISSUE TITLE
Privacy and cookies: Write a short summary that expresses Vega's values

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vega.xyz#274]
## The Chore

Write a human-readable summary of the (long!) privacy and cookies policy, that emphasises how Vega's values of privacy and anonymity.

## Tasks

- [ ] Draft
- [ ] Visual design: make this section a bit more interesting, clearly differentiated from the main body of the policies
- [ ] Team/stakeholder review (including Dave and Barney)
- [ ] Implement

## Additional details / background info
- Create a succinct, human readable summary of the privacy and cookies policy, which also expressed Vega's values and beliefs about privacy e.g. we believe in privacy and anonymity, it's important to us, so unless you sign up for something we capture or process your data. And if you do, we only do precisely what you've asked for.
- We don't use any cookies whatsoever. The only thing we store is your preference for light/dark mode, and language, and these use local storage in your browse, not cookies.
- We don't use any third party analytics service such as google analytics, we use only server logs, never tied to an individual.

**Comment by maryvaliakas** [comment]
Heya! 

Doc is here: 

https://docs.google.com/document/d/1lfIKJIgUeJqYIPkz9we1eUO3E2jiIm0al_Wnw_CmuG8/edit?usp=sharing

**Comment by pennyandrews** [comment]
Closing this ticket as have merged the detail with https://github.com/vegaprotocol/vega.xyz/issues/371
