### ISSUE TITLE
EXPLORE THE DOCS link not correct vega.xyz/develop

### ISSUE THREAD

**Issue by duythien0912** [vegaprotocol/vega.xyz#281]
## Description

On page https://vega.xyz/develop when I click on "EXPLORE THE DOCS" it show Page Not Found on https://docs.vega.xyz/concepts/new-to-vega/

## Steps to Reproduce

1. Go to 'https://vega.xyz/develop'
2. Click on 'EXPLORE THE DOCS'
3. See error

## Expected behavior

Should show page https://docs.vega.xyz/mainnet/concepts/new-to-vega

## Screenshots

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/20185622/197512386-4eeaa95b-75be-4584-ad8b-004157c397de.png">

## Device details

**Desktop (please complete the following information):**

**Comment by candida-d** [comment]
Thanks for raising this @duythien0912!

**Comment by pennyandrews** [comment]
This has now been resolved and is working correctly on https://vega.xyz/develop
