### ISSUE TITLE
URLs for fairground latest release and mainnet latest release to be used by the website

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#317]
## Chore

On [this website page for the wallet](https://vega.xyz/wallet/) we have one button with a drop down pointing to the latest version per OS for the desktop wallet i.e. this URL
https://github.com/vegaprotocol/vegawallet-desktop/releases/latest/download/vegawallet-desktop-darwin-amd64.zip 
We now need a way to download a different version for Mainnet or Testnet e.g. two button / drop downs: [ Download desktop app (Mainnet) ] and [ Download desktop app (Testnet) ]

This chore is to provide two unique URLs / places for the website to point to for downloading the latest desktop wallet version for each of fairground and mainnet.

 E.g. Will there be a "latest-mainnet/download" "latest-testnet/download" or "download/vegawallet-testnet-desktop-darwin-am64.zip" or something else? :upside_down_face:

**Comment by ValentinTrinque** [comment]
The `latest` link to release is fine for mainnet, _for now_, as it will link to the latest release (not pre-release) available on the repository. However, the version for testnet should be updated only when the testnet upgraded to the version the wallet supports. So it will probably require clever resolution of the testnet version to point to the right version of the vegawallet.

**Comment by ValentinTrinque** [comment]
As the moment I write this comment the latest pre-release links can be found there:
https://github.com/vegaprotocol/vegawallet-desktop/releases/tag/v0.3.0

**Comment by ValentinTrinque** [comment]
Unassigning myself as I think it requires to much work from me that is out of my scope.
