### ISSUE TITLE
Dead Link on https://vega.xyz/market-creation/ - Attract Liquidity

### ISSUE THREAD

**Issue by Ben-peoplemake** [vegaprotocol/vega.xyz#346]
## Steps to Reproduce

1. Go to https://vega.xyz/market-creation/
2. Scroll down to 'attract liquidity'
3. Click on 'attract liquidity'
3. Click on '[Read the docs about liquidity provision (Testnet)](https://docs.vega.xyz/testnet/tutorials/providing-liquidity)' link
5. See error

## Screenshots
<img width="792" alt="Screenshot 2022-11-15 at 20 16 44" src="https://user-images.githubusercontent.com/117179940/202017181-ee8795c0-a48c-4152-bf57-29dfa4c5d3d7.png">
<img width="956" alt="image" src="https://user-images.githubusercontent.com/117179940/202017764-48be184e-5f32-42e8-a990-78bb2c5c6faa.png">

## Additional context

There is no providing liquidity section in the documentation: https://docs.vega.xyz/testnet/tutorials

**Comment by pennyandrews** [comment]
This link has broken due to the docs team renaming liquidity provision to committing liquidity. I've fixed this in the linked PR
