### ISSUE TITLE
Link to provide feedback on Github

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#360]
Add link to [Provide feedback ↗] (https://github.com/vegaprotocol/feedback/discussions)

This contribute section is in a couple of places so needs to be added to both,  footer too?

![Image](https://user-images.githubusercontent.com/46783148/203028817-8aa9c725-d21d-4f2e-a120-2852ec343fd2.png)

![Image](https://user-images.githubusercontent.com/46783148/203029202-63d672b2-9994-454e-a04d-70732c8b79c2.png)

**Comment by goslingo** [comment]
@ckpringle

Ready for review:
https://deploy-preview-363--vega.netlify.app/

See "Provide feedback" link in header and footer under "Community"

**Comment by pennyandrews** [comment]
I had a look at this PR https://github.com/vegaprotocol/vega.xyz/pull/363 and it looks fine, but has merge conflicts so I wasn't able to approve
