### ISSUE TITLE
'Automatically' always show latest blog post

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#386]
## The Chore

Update blog posts to work client-side to ensure always up to date. 

Ways we could work around it:
Schedule a build every 24 hours (we prefer this one)
Get a proxy set up

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by goslingo** [comment]
I had this working and ready to go, however it seems that Medium is protected via Cloudflare with a JS challenge page.

After working okay for several hours, the JSON feed started returning an interstitial page requesting for Javascript and cookies to be turned on with the following message "medium.com need to review the security of your connection before proceeding".

I'm not sure when this challenge occurs, perhaps when Medium is suffering a DDOS attack, however it means that there is no reliable way of consistently fetching latest posts from Medium.

This may also explain why posts might not have been previously been updated even after the site was rebuilt.

_Correction_ there might be one way of fetching latest posts, but it requires setting up a CloudFlare worker:
https://github.com/alekrumkamp/medium-feed-json

**Comment by ckpringle** [comment]
Discussed in standup that we could alternatively we make it easier for someone to manually update the latest news blog post (homepage) each time we want it to change. There are three posts on the develop / get started page that we could just remove. @rebeccajsimmonds what you think?
