### ISSUE TITLE
REWARDS: Placeholder indication of what should be there when there is no real data

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#391]
## The Chore

Find a way to be able to put the rewards page live that shows you the sort of data / shape of data you would expect to see on the page when there isn't real data (and it is clear it isn't real)

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by joellecharlotte** [comment]
Here is the placeholder state if there is no data to display: [Figma link ↳ ](https://www.figma.com/file/AlPkMuAwHtfSQCeaZRrpkv/Develop?node-id=2043%3A10364&t=WflUAEeC1iOsUXlj-1)

Icon + $Vega with the text "Coming soon" below it.

Attached is the icon used for the placeholder state @2x

![Image](https://user-images.githubusercontent.com/113684458/206124021-714c3d0a-adcc-458d-989d-960365533a72.png)
