### ISSUE TITLE
Update site-preview image for Vega.xyz

### ISSUE THREAD

**Issue by bigfandavid** [vegaprotocol/vega.xyz#409]
## The Chore

In looking at the site-preview image for docs, we are aware how out of date the main vega.xyz image is. This should be updated to align with the new docs version and better reflect the latest website design.

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by bigfandavid** [comment]
Proposed design.
![Vega xyz Preview Image](https://user-images.githubusercontent.com/113683891/211516256-39d73e0b-e70d-4d6e-9811-5cafc7124ca6.jpg)

**Comment by pennyandrews** [comment]
Rebecca signed off
