### ISSUE TITLE
Builders Club event list out of date

### ISSUE THREAD

**Issue by rebeccajsimmonds** [vegaprotocol/vega.xyz#413]
## The Chore

Remove the event from the builders club 'what's going on' list as it happened in October.

## Tasks

- Check with Sunny that we are OK to remove this
- Update list with any upcoming events
- If no events let's put in a message 'Check back later for more events'

**Comment by pennyandrews** [comment]
Events are managed in notion and pulled into the website via an integration. So the community team need to make any updates for the events lists and these magically reflect on the website so no work for the website team on this. 

In the event of no events, I believe we already handle this in a couple of ways, as part of our automated tests, if there are less than a certain number of events, we trigger an email to the community team to flag this. And I believe we already have something that handles if there are none but I can't remember what that is, @goslingo can you advise here?
