### ISSUE TITLE
Link to mainnet incident reports

### ISSUE THREAD

**Issue by rebeccajsimmonds** [vegaprotocol/vega.xyz#416]
## The Story

As a user 
I want to be able to find all incident reports that Vega have published
So that I can understand current issues, their status and get a feel for how Vega responds to them

## Tasks

- [ ] Add link in website footer to 'Mainnet status & incidents' https://blog.vega.xyz/tagged/vega-incident-reports

## Additional details / background info
(https://vegaprotocol.slack.com/archives/C02GZ0Q0NDC/p1673003925560669)

**Comment by rebeccajsimmonds** [comment]
We discussed this on the stand-up on Wednesday. It is still blocked @goslingo? What is the issue?

**Comment by goslingo** [comment]
@rebeccajsimmonds I looked at pulling in from Medium but I think it's a no go unfortunately...

While Medium offers a public feed, it only returns the latest ten posts and can't be filtered. Their API allows only for publishing posts and not fetching content. I guess they don't want people using them as a CMS.

An alternative might be to mirror incident reports on Notion and add in the URL that points to the corresponding post on Medium. Although it's not ideal to have to publish content in both places.

**Comment by pennyandrews** [comment]
@rebeccajsimmonds I have chatted to Gordon briefly and there is not currently a 'known' issues list that would make sense to link to and therefore I think we should keep this ticket simple and just about linking to Medium for the incident report articles. Once the bug bounties stuff (including known issues) is ready we can include adding that on the page or somewhere else etc.
