### ISSUE TITLE
When there are no future events, display a nice message

### ISSUE THREAD

**Issue by goslingo** [vegaprotocol/vega.xyz#433]
## Description

When the events feed isn't returning any future events, make sure we show a message in situ on the homepage saying there are no events.

At the moment the site throws an uncaught exception. This in turn causes a failing test in cypress.

## Expected behavior

A message stating that there are no events.

## Screenshots

<img width="1533" alt="Screenshot 2023-01-23 at 09 28 52" src="https://user-images.githubusercontent.com/1823553/214005944-5ee176b1-b8cc-4f9d-88b2-f7019217c474.png">

<img width="646" alt="Screenshot 2023-01-23 at 09 27 33" src="https://user-images.githubusercontent.com/1823553/214005641-dd62e47f-9b9f-40b8-89b8-7d4dda1cbab6.png">

**Comment by maryvaliakas** [comment]
Copy can be:

Things are a little quiet. Check back to see what's on.
