### ISSUE TITLE
Stats design for each mainnet sims

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#442]

**Comment by bigfandavid** [comment]
Established format for individual stats so they can be uploaded to Twitter as single images, in pairs, or in sets of four images.

First four 'stat slides' completed and sent for feedback.

![Image](https://user-images.githubusercontent.com/113683891/217476047-53cdb9f4-99e7-46d2-84f8-2f20af2cbffa.png)

![Image](https://user-images.githubusercontent.com/113683891/217476049-d55de994-2ccb-4d76-b5b7-5ec549ff7e7f.png)

**Comment by bigfandavid** [comment]
Stats for Sim 1 have been completed and signed off.

This story on hold now until the next Sim is complete - this will fall outside of this sprint so will place story into new to triage(?) @pennyandrews

![Image](https://user-images.githubusercontent.com/113683891/218055189-cef7b795-969a-459b-9431-de8a23f10cee.jpg)
![Image](https://user-images.githubusercontent.com/113683891/218055187-1bac693c-5f76-4c05-b382-8465df49fd81.jpg)
![Image](https://user-images.githubusercontent.com/113683891/218055188-b981b11c-0d22-4065-b21d-9d0fa96b343f.jpg)
![Image](https://user-images.githubusercontent.com/113683891/218055186-d6aaf338-43d5-401f-8861-2a60abe8a205.jpg)
![Image](https://user-images.githubusercontent.com/113683891/218055191-86468dba-337a-4159-8f00-bbccb914648e.jpg)
![Image](https://user-images.githubusercontent.com/113683891/218055190-25cbe76b-48c4-467e-8f64-fa6fa7b956db.jpg)
![Image](https://user-images.githubusercontent.com/113683891/218055192-9820a96e-01e2-41db-9acf-440c652880ae.jpg)
