### ISSUE TITLE
https://vega.xyz/validators - stand by validator number incorrect

### ISSUE THREAD

**Issue by rebeccajsimmonds** [vegaprotocol/vega.xyz#574]
https://vega.xyz/validators is showing we have 0 stand-by validators when we have 1. The data might be pulling from block explorer. 

![Image](https://github.com/vegaprotocol/vega.xyz/assets/42541523/a3735d5f-da09-4bba-8e35-e0cf56884e98)

**Comment by edd** [comment]
This will be fixed by #573
