### ISSUE TITLE
Fairground content update

### ISSUE THREAD

**Issue by rebeccajsimmonds** [vegaprotocol/vega.xyz#575]
- Can we remove the words ' The Mainnet Sims are live! Get involved and earn rewards on' from https://fairground.wtf/

- The text should read 'Fairground, the official testnet of Vega.' and then the paragraph break and keep 'free from the risk of trading etc' the same

- Last paragraph edit 'Participate in `the mainnet sims `to earn rewards for helping to find bugs and battle harden Vega.' to 'Participate in `incentives` to earn rewards for helping to find bugs and battle harden Vega.

**Comment by rebeccajsimmonds** [comment]
![Image](https://github.com/vegaprotocol/vega.xyz/assets/42541523/d62f7130-7077-496e-9710-f54c27f0b1dd)

**Comment by daunatv** [comment]
Closed with https://github.com/vegaprotocol/fairground/pull/352
