### ISSUE TITLE
Repoint Fairground url

### ISSUE THREAD

**Issue by rebeccajsimmonds** [vegaprotocol/vega.xyz#585]
We need to have console.fairground.wtf point to trading.fairground.wtf for now. 

We will change the url in the next few days but for now repoint

**Comment by goslingo** [comment]
@rebeccajsimmonds 

I'm don't think is relevant as we won't have any links to console.fairground.wtf on vega.xyz anymore. However we do have a link to the Fairground website in the header navigation.
