### ISSUE TITLE
More issues on https://vega.xyz/validators/ ...

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega.xyz#599]
1. The "reward multiplier" for standby of `` (currently = 0.85) should be shown.  But for consensus validators the corresponding number is `1.0` and always will be. The number `network.validators.incumbentBonus` is related to how / when standby gets promoted to a consensus validator.
<img width="872" alt="image" src="https://github.com/vegaprotocol/vega.xyz/assets/62546419/a880be06-d50e-49e2-9eab-4d5cd86dad23">
The reward multiplier text also makes little sense:
<img width="820" alt="image" src="https://github.com/vegaprotocol/vega.xyz/assets/62546419/961cd39a-78b1-4885-8feb-b22ff3463d71">

2. The number of maximum consensus validators is set by `network.validators.tendermint.number` not by  
<img width="1229" alt="image" src="https://github.com/vegaprotocol/vega.xyz/assets/62546419/19a996f4-f4ff-4f2f-942f-e4e4c489546d">

**Acceptance Criteria** 

1. The tooltip for Limit x Standby Validators shoud be "This value is determined by the network parameter `network.validators.ersatz.multipleOfTendermintValidators` multiplied by the network parameter `network.validators.tendermint.number`"
2. The tooltip for Limit x Consensus validator should be "This value is determined by the network parameter `network.validators.tendermint.number`"
3. The value in Reward Multiplier x Consensus validators should be hardcoded to 1 
4. The tooltip for Reward Multiplier x Consensus validators should read "This value is always set to 1 for Consensus validators" 
5. Text under ** should be changed to "Consensus validators secure the network and therefore earn rewards. Standby validators are ready to step up and fill open consensus validator slots and therefore are also rewarded by the protocol.  However their share of rewards is penalised relative to consensus validators by a factor of x0.85" 
6. In the text under ** therefore the first network param of 0.05 is removed entirely, the second one of 0.85 currently has an accurate tooltip so no change.

**Comment by pennyandrews** [comment]
Hey @davidsiska-vega @JonRay15 are you able to help write out some more explicit rules for these numbers to help Oli implement the changes effectively? Thank you!!!

**Comment by JonRay15** [comment]
Done
