### ISSUE TITLE
Public key is expired

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega.xyz#673]
## Description

Discussion in Slack https://vegaprotocol.slack.com/archives/C03GJPCERFY/p1686851203410439

## Steps to Reproduce

1. Go to 'Report a security issue'
2. Fill in a bug report
3. Open network panel
4. Submit error

## Expected behaviour

I see a success message
And an email is sent

**Comment by pennyandrews** [comment]
Gordon has kindly offered to update the website and security policy once a new key, or expiry extended for existing key is sorted
