### ISSUE TITLE
Announcement banner for Console deployment

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#688]
## The Chore

Update the banner with something pushing people towards the blog that promotes the new deployment 1 and console features. 

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by JonRay15** [comment]
What are we saying we'd put here?

This sounds like it would be some text promoting the new deployment, maybe with a link to the new features thatr have been deployed,
