### ISSUE TITLE
Use quantum formatting in LP Dashboard

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#707]
## Story 

As a team 
We want to tidy up the decimal points in the LP dashboard
So that it is easier to read 

## Background

Quantum formattign should be used on all settlement asset decimals fields. Defined as:

`Number DP = MAX(0, LOG10(100/Quantum))`

Probably for the LP dashboard we'd want to show even fewer DP cos the expected order of magnitude is higher, so for USD we'd show 0 DP, and would only show it on larger coins like BTC / ETH.  If so

`Number DP = MAX(0, LOG10(1/Quantum))`

Console are working on something here so we should be able to leverage it once done.  The tickets for that are here, speak to Madalina for implementation details if needed. Hopefully this is a quick win....

https://github.com/vegaprotocol/frontend-monorepo/issues/2132

## Acceptance Criteria

- Last Price - Take from `decimals` on the market API 
- Change - Take from `decimals` on the market API 
- Volume - use `quantum formatting` 
- Total Staked - use `quantum formatting` 
- Target Stake - use `quantum formatting`
- %age Target Stake - 0 DP 
- Fee Level - show raw value but always trim trailing zeroes
- There is a way to see the full number if I want to know the fully accurate number (e.g. with a tooltip)
- The health bar figures shown in asset decimals are also formatted this way (target stake & auction level)

**Comment by JonRay15** [comment]
This is now lower priority as #1071 puts a simpler implementation in place that as long as all markets settle in USDT (which they currently do) will cover us.
