### ISSUE TITLE
Add volume spark line

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#710]
* Spark line beside volume ???
Best thing would be a spark line of up to one month growth - trend of volume - should be a library already in console in the market popup

Weeks can exhibit seasonality... most recent 24h volume + spark line is fine

We do have volume by day on the console, so this must be availalble, check with them how to source.

![Image](https://user-images.githubusercontent.com/89918817/210785993-4610c1e1-1bd5-42db-acf1-8f1424a2a713.png)

**Comment by JonRay15** [comment]
This is now covered under another ticket
