### ISSUE TITLE
Utilise common announcement banner component

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#720]
## The Chore

Botond very kindly made the announcement banner a common published component [in a repo here](https://github.com/vegaprotocol/announcements) that can enable us to update the announcement in one place and reflect automagically on all Vega frontends (see ticket for reference vegaprotocol/frontend-monorepo#3244)

If we continue to use this banner regularly, it would be great to update the website vega.xyz (and possibly the wallet too?) to  consume it so that we can show the same banner message across all Vega frontends at all times, minimising the overhead of each update.

## Tasks

- [ ] Update vega.xyz to use the common announcement component
- [ ] QA Test
- [ ] Release

## Notes / Additional Info

<img width="1508" alt="Screenshot 2023-03-22 at 11 18 53" src="https://user-images.githubusercontent.com/47143694/226888896-54f05b97-8f83-4102-b4e2-1641a34cede2.png">

<img width="1506" alt="Screenshot 2023-03-22 at 11 18 39" src="https://user-images.githubusercontent.com/47143694/226888909-f0e09159-0715-408b-8ff6-8a31c5cd7c2f.png">

<img width="1512" alt="Screenshot 2023-03-22 at 11 18 28" src="https://user-images.githubusercontent.com/47143694/226888918-afafe698-1357-4ef8-a83a-0da6e2350c72.png">

<img width="1506" alt="Screenshot 2023-03-22 at 11 18 13" src="https://user-images.githubusercontent.com/47143694/226888922-356125bd-a46a-4ed0-8112-9621f7bb7656.png">

**Comment by JonRay15** [comment]
This is done / redundant
