### ISSUE TITLE
Enable network switching for vega.xyz for testing new features

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#728]

**Comment by pennyandrews** [comment]
Ciaran to verify that we can do this now and if so then we can document and close

**Comment by ciaran-** [comment]
We can switch what network the pages point to via this env variable:
`GATSBY_VEGA_API`
e.g. `https://api.vega.community/graphql` vs `https://api-testnet.vega.rocks/graphql`
