### ISSUE TITLE
Update list of proposal types for Deployment 1 features

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#731]
## Story

As a Vega user
I want to be able to see an accurate list of Governance proposal types on the Vega network 
So that I know how I can contribute to / influence the network

https://vega.xyz/governance/

![Image](https://github.com/vegaprotocol/vega.xyz/assets/47143694/ca04bd70-5d39-4af8-a21d-b675c347a003)

## Acceptance Criteria

- [ ] I can see Governance Initiated Transfers as one of the types of proposal possible to make on Vega

Proposed text:

"As a token holder, you can submit a proposal to create or update a market, create or update a settlement asset, change network parameters, initiate a transfer of funds from the treasury, or make a freeform proposal (for changes that will not change network behaviour)."

## Tasks

- [ ] Copy
- [ ] Team and stakeholder review
- [ ] Implementation 
- [ ] Testing
- [ ] Release

**Comment by JonRay15** [comment]
This got bumped to deployment 2
