### ISSUE TITLE
Shareable output with performance data (referral site)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega.xyz#809]
## User Story 

As a team creator / referral code maker 
I want an easy way to share my teams key stats 
So that I can attract more team members

## Acceptance criteria 
- [ ] There is a way to create a shareable image / tile or meta data that includes performance data e.g. top savings, top rewards etc
- [ ] When it's shared, it's easy for potential team members to digest e.g. easily copy pasted into a twitter post or similar 

## Additional details / background info

![Image](https://github.com/vegaprotocol/vega.xyz/assets/46783148/ba720004-5a6a-45d2-8484-ec5b9e5b933a)

**Comment by JonRay15** [comment]
Consumed this into another ticket
