### ISSUE TITLE
Latest tweet not loading

### ISSUE THREAD

**Issue by goslingo** [vegaprotocol/vega.xyz#824]
## Description

The latest tweet on the home page isn't loading. After investigation, we're getting the error "Too Many Requests".

Twitter has introduced rate limiting on its API, and since we're not caching our response when we call their API, we're obviously busting through the limit.

## Suggested fix

In order to fix this, I suggest we use Redis to cache the latest tweet which we can update at a specific interval (perhaps hourly). We can setup Redis easily on Vercel.

**Comment by JonRay15** [comment]
Will be fixed by the redis cache work
