### ISSUE TITLE
Wallet download page suggested I download the AMD wallet on my M1 machine

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vega.xyz#91]
https://vega.xyz/wallet/ defects what system you are on and gives you a primary download button based on your machine but I think it is suggesting the wrong version for my Mac (an M1).. it suggests https://github.com/vegaprotocol/vegawallet-desktop/releases/download/v0.1.1/vegawallet-desktop-darwin-amd64.zip I think M1 is ARM

**Comment by pennyandrews** [comment]
We currently manage all the vega.xyz work on Asana so I have created a ticket for this here https://app.asana.com/0/1201793103707836/1202469302417669/f to avoid this getting lost. 

I know one day when we are encouraging the community to get more involved in the website we will have to change this, but for now, this is where we are planning and tracking our work. Thanks
