### ISSUE TITLE
Improve 'Use Vega' new user onboarding

### ISSUE THREAD

**Issue by daignrd** [vegaprotocol/vega.xyz#925]
## Story
As part of the ongoing work to revamp vega.xyz for September/October, I think user onboarding can improve.

Website UX improvements:
It would make a lot of sense to have a section before ‘Use the network’ that onboards new users (before ‘Tools built on Vega’)

When I click 'Use' the network, instead of reducing friction and immediately telling me what I need to use Vega, I'm presented with lots of tools. Who knows what I actually need?
<img width="1479" alt="image" src="https://github.com/vegaprotocol/vega.xyz/assets/67317923/e4882194-202d-4b3b-ae77-835bf0a2a542">

This is why the Community Team recommend a section above the tools that illustrate or explain the TLDR on how exactly you can get started as a completely new user who wants to use the network for the first time

## Acceptance Criteria

- [ ] I can work out how to use Vega when I click 'Use Vega'

**Comment by JonRay15** [comment]
Covered under #972
