### ISSUE TITLE
Combine insights & talks

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega.xyz#977]
Simply combine these two pages

https://vega.xyz/insights

https://vega.xyz/talks

Feel like we need to tweak the presentation as a result of this ... but dont know exactly how ... suggest you have a play and come back with something.

**Comment by goslingo** [comment]
@bigfandavid I've combined insights and talks on to one page, you can see it here:
https://vega-6xysmx88y-vegaprotocol.vercel.app/insights/

Any suggestions on improving design welcomed, in particular the prev and next links.

**Comment by JonRay15** [comment]
David is doing some design work on this page too, so maybe we wait for that before anyone reviews.
